name: release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm ci
      - run: npm run compile
      - run: npx vsce package
      - uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: "*.vsix"

  publish-marketplaces:
    if: startsWith(github.ref, 'refs/tags/')
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm ci
      - run: npm run compile
      - name: Publish to VS Code Marketplace
        run: npx vsce publish --no-dependencies
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - name: Publish to Open VSX
        run: |
          npx vsce package
          npx ovsx publish --packagePath $(ls *.vsix)
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
