name: release
on:
  push:
    tags:
      - "v*.*.*"      # runs only on tag pushes (v0.0.3 etc.)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm ci
      - run: npm run compile
      - name: Package VSIX
        run: npx --yes vsce package --no-dependencies
      - name: Verify VSIX
        run: test -n "$(ls -1 *.vsix 2>/dev/null)"
      - uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: "*.vsix"

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm ci
      - run: npm run compile
      - run: npx --yes vsce package --no-dependencies
      - name: Verify VSIX
        run: test -n "$(ls -1 *.vsix 2>/dev/null)"
      - name: Create GitHub Release with VSIX
        uses: softprops/action-gh-release@v2
        with:
          files: "*.vsix"
          generate_release_notes: true
          fail_on_unmatched_files: true
